### ISSUE TITLE
Add link to translations

### ISSUE THREAD

**Issue by astrojuanlu** [yamila-moreno/pepa#7]
This is the Transifex project:

https://www.transifex.com/pepa-1/pep-a/

And BTW, the badge in the readme looks broken to me.

@xmnlab

**Comment by yamila-moreno** [comment]
I think I don't really understand this as an issue or how to fix it. Could you provide more detail? Thanks! :D

**Comment by yamila-moreno** [comment]
the url seems to be work and according to this link https://www.transifex.com/pepa-1/pep-a/widgets/ the url is ok.

**Comment by astrojuanlu** [comment]
According to that link the URL is OK, but I don't see a rendered image in the readme and when I click it I get an "Error Fetching Resource" error and stops there...
